log_level: "info"
file_size_limit: 10485760
presigned_url_expiration: 60

s3:
  endpoint_url: "http://localhost.localstack.cloud:4566"
  bucket_name: "flowvision-test-bucket"

app_server:
  port: 8000
  app: "routes:app"

# vision_model: "gpt-4o"
vision_model: "Qwen/Qwen2-VL-2B-Instruct"
gpu_type: "cuda"

image_resizing:
  width: 800
  height: 1000

image_crop:
  left: 0.1
  top: 0.2
  right: 0.9
  bottom: 0.8

logs:
  api_logger:
    path: "logs/api_logs"
    name: "FlowVision"
  feedback_request_logger:
    path: "logs/feedback_request_logs"
    name: "FeedbackRequest"
  extraction_request_logger:
    path: "logs/extraction_request_logs"
    name: "ExtractionRequest"
