log_level: "info"
file_size_limit: 10485760
presigned_url_expiration: 60

s3:
  endpoint_url: "http://localhost.localstack.cloud:4566"
  bucket_name: "flowvision-test-bucket"

app_server:
  port: 8000
  app: "routes:app"

# vision_model: "gpt-4o"
# vision_model: "Qwen/Qwen2-VL-7B-Instruct"
vision_model: "InceptionV3"
gpu_type: "cuda"

image_resizing:
  width: 1000
  height: 1000

image_crop:
  left: 0.1
  top: 0.2
  right: 0.9
  bottom: 0.8

logs:
  api_logger:
    path: "logs/api_logs"
    name: "FlowVision"
  feedback_request_logger:
    path: "logs/feedback_request_logs"
    name: "FeedbackRequest"
  extraction_request_logger:
    path: "logs/extraction_request_logs"
    name: "ExtractionRequest"

database:
  host: localhost
  port: 5432
  dbname: "flowvision"
  username: postgres
  password: postgres


# Model paths
models:
  bfm_classification: "/path/to/src/models/bfm_fastai"
  individual_numbers: "/path/to/src/models/individual_number_recognition_yolo11l.pt"
  color_classification: "/path/to/src/models/color_classification_fastai"

# Image processing parameters
image_enhancement:
  clahe_clip_limit: 2.0
  clahe_tile_grid_size: [8, 8]
  sharpening_alpha: 1.5
  sharpening_beta: -0.5
  color_boost_alpha: 1.1
  color_boost_beta: 10

# Test image paths
test:
  sample_image: "dataset/data_cleaned/classification_data/Good/20240909121001_C2268402_F20918_M7711086.png"
